# Numpy Skills

Have a few challenges that we will approach to solve using Numpy codes and methods.

#### we will start with importing Numpy library 

In [1]:
import numpy as np

#### creating arrays with only ones, zeros 

In [3]:
np.ones(10) 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### creating an array with defined values from 10 to 40

In [8]:
np.arange (10,41)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [9]:
np.arange(10,41,5)

array([10, 15, 20, 25, 30, 35, 40])

#### Creating a known range array and shaping it at same time 

In [10]:
np.arange(25).reshape (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### creating an array with random numbers with the value between 0 and 1, and putting it in a 2-dimensional array

In [13]:
np.random.rand(25).reshape(5,5)

array([[0.34379021, 0.95232539, 0.42277554, 0.01210707, 0.70315967],
       [0.49778401, 0.89486796, 0.63543811, 0.63171566, 0.67374153],
       [0.58600217, 0.14943144, 0.36711024, 0.22094175, 0.4212941 ],
       [0.18631771, 0.36079691, 0.0691003 , 0.15852072, 0.96290796],
       [0.03999046, 0.6053238 , 0.81215621, 0.3754287 , 0.03853721]])

#### creating an array with identified values from 0 to 10, putting them into a 2-dimensional matrix, and shaping it 

In [16]:
np.linspace (0,10,100).reshape(10,10)

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
         0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
         1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
         2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
         3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
         4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
         5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
         6.56565657,  6.66666667,  6.76767677

#### creating an array between 1 and 7 with 20 equal points. 

In [17]:
np.linspace(1,7,20)

array([1.        , 1.31578947, 1.63157895, 1.94736842, 2.26315789,
       2.57894737, 2.89473684, 3.21052632, 3.52631579, 3.84210526,
       4.15789474, 4.47368421, 4.78947368, 5.10526316, 5.42105263,
       5.73684211, 6.05263158, 6.36842105, 6.68421053, 7.        ])

In [18]:
np.linspace(1,7,20).reshape(5,4)

array([[1.        , 1.31578947, 1.63157895, 1.94736842],
       [2.26315789, 2.57894737, 2.89473684, 3.21052632],
       [3.52631579, 3.84210526, 4.15789474, 4.47368421],
       [4.78947368, 5.10526316, 5.42105263, 5.73684211],
       [6.05263158, 6.36842105, 6.68421053, 7.        ]])

#### Arrays indexing and slicing 

In [24]:
arr = np.arange(1,26).reshape(5,5)

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
### selecting number 1 
arr [0,0]

### selecting number 12 
arr [2,1]

### selecting number 24 
arr [4,3]

24

In [38]:
### Select a range the second and third rows with three middle culomns only

arr[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [36]:
### Select a range the last tworows with last culomn only

arr [3:,4:]

array([[20],
       [25]])

In [37]:
arr [1:4,2:5]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

#### Arrays Opersations 

In [39]:
### sum of all values in arr

arr.sum()

325

In [40]:
### sum of values in certain column 

arr.sum(axis=0)

array([55, 60, 65, 70, 75])

### - - - - The end - - - -